### ISSUE TITLE
Excelファイルについて

### ISSUE THREAD

**Issue by ShotaroImai** [IR-Platform/IR-data-project#5]
エクセルの分析ありがとうございます。githubからダウンロードしてみたのですが、ファイルが壊れてしまっているようです。もしかしてgithubにエクセルをアップロードするのはダメですかね?

**Comment by AquilaITOH** [comment]
Excelファイルについて、手元の環境では再現しませんでした。windows PCでも確認しています。ひとつ気になっているのはExcel2021/ M/S 365で導入された新しい関数(=FILTER())を使っている点です。互換性の問題が少なそうな解析例を作りました。こちらはいかがでしょうか？
[scripts/Excel/dataset000_histogram_basic.xlsx](https://github.com/IR-Platform/IR-data-project/blob/main/scripts/Excel/dataset000_histogram_basic.xlsx)

**Comment by ShotaroImai** [comment]
script/Excelにアップされているファイルのうち、000.xlxs、100.xlsx、200.xlsxに関してはファイルの破損が見られるようです。それ以外のdatasetからはじまるファイルに関しては問題ありませんでした。
ファイルのダウンロードについてですが、cloneはせずにフォルダへアクセスして直接ダウンロード(右クリックやソーステキスト画面から)を試みた結果です。gitに慣れていないユーザーを想定した動作です。これが何か影響しているかもしれません。

**Comment by tosshi-dev** [comment]
説明不足でした。
サンプルファイルはディレクトリの構成を指し示すものであり、中身はそもそもありませんでした。
また、ファイル名も修正しましたので、本問題は解決しました。
